### PR TITLE
Avoid destroying the offering form when attributes change

### LINKED ISSUE #2838: Instructor Picker for Offering fails when desired name is already listed as Course Director
It works the way it should be working when assigning instructors to ILM's. The ILM Instructor selector is working fine. The standard Offering Instructor picker is NOT.

See below ... 

"Stan Fields" is a Course Director as shown below.

image

# ILM ...

"Stan Fields" can be added as Instructor for the ILM as shown below.

image

image

When an User is already assigned as Director for a Course, that user can't be added as Instructor for an Offering in that Course.  Conversely, when a User is already added as Instructor for an Offering, they CAN still be added as Director for the Course.

# Standard Offering

Running a search for "Stan Fields" blows up. It does not say no records returned. It does not provide other results. "Stan Fields" cannot be added because he is a Course Director in this Course.

image

And then ...

No "Stan" - no results at all - "Stan" can't be added.

image

### PR DESCRIPTION
**Pull request by jrjohnson**
By removing this check we avoid a re-render anytime something is loaded
or changed. Specifically this was an issue when some users attached to a
course as a director were queried from the API. It would cause a
re-render which destroyed the search box.

Fixes #2838

### CODE REVIEW

**Comment by jrjohnson** [comment]
Deploy preview for *ilios-frontend* ready!

Built with commit 78ff7b2aea4b9f62c8a1a82c520ce43b13d510ec

https://deploy-preview-3479--ilios-frontend.netlify.com

**Comment by dartajax** [comment]
image

So Dabney and Pharm1 are directors of this course. 

Add Dabney (or Nic Gutierrez if Dabney is not available).

image

As soon as you starting searching for Pharm, Dabney is already removed from the list of instructors.

**Comment by dartajax** [comment]
Dabney is missing - Pharm remains.

image

**Comment by dartajax** [comment]
If you save them individually, it appears to work. This is probably not the most logical workflow for users since they may add a number of instructors at the same time.

File: app/components/user-search.js [hunk 1]
```diff
@@ -42,7 +42,7 @@ export default Component.extend({
   roles: '',
   availableInstructorGroups: null,
   currentlyActiveInstructorGroups: null,
-  search: task(function * (searchTerms = '') {
+  search: task(function* (searchTerms = '') {
```
Comment (stopfstedt) [inline app/components/user-search.js]: why?

Comment (jrjohnson) [reply app/components/user-search.js]: VSCode must have done that for me. 😠

Comment (jrjohnson) [reply app/components/user-search.js]: Fixed.

**Comment by dartajax** [comment]
This now appears to work as it should. Shall I merge it?
