### PR TITLE
ensure trailing slash on host-portion of rollover endpoint.

### LINKED ISSUE #2268: course rollover url broken when proxying to backend
this is a regression that happened after moving backend config into `.env`. we've lost the trailing slash.

selection_038

### PR DESCRIPTION
**Pull request by stopfstedt**
fixes #2268.

### CODE REVIEW

**Comment by jrjohnson** [comment]
Deploy preview ready!

Built with commit 4899235390a753d1197f14c08e3738a73e2d722b

https://deploy-preview-2269--ilios-frontend.netlify.com

File: app/components/course-rollover.js [hunk 1]
```diff
@@ -79,7 +79,7 @@ export default Component.extend(ValidationErrorDisplay, Validations, {
     if (expandAdvancedOptions && skipOfferings) {
       data.skipOfferings = true;
     }
-    const host = this.get('host')?this.get('host'):'/';
+    const host = this.get('host') ? (this.get('host').replace(/\/+$/, '') + '/') : '/';
```
Comment (jrjohnson) [inline app/components/course-rollover.js]: This feels like it can be applied generally and belongs in the config service instead of dealing with it every time we ask for the host somewhere.

Comment (jrjohnson) [inline app/components/course-rollover.js]: Doing this would also fix #2243

**Comment by stopfstedt** [comment]
ok, then how about assuming no trailing slash _always_? 

our home-grown config service does not read environment variables; this is handled via third-party vendor lib [ember-cli-servervariables](https://github.com/blimmer/ember-cli-server-variables). now, we could wrap around this service and provide a `getBackendHost()` method that would append the trailing slash on, but IMO that's not worth the troubles.
