### PR TITLE
prevent deletion of learner groups with associated learners

### LINKED ISSUE #2713: Delete Learner Group Fails When Sub Groups with Members Exist
See below ...

image

After clicking as shown above ...

image

And then ...

Failure.

image

### PR DESCRIPTION
**Pull request by stopfstedt**
fixes #2713 

in case a given group has learners, or any of its sub-groups has learners, we'll just render a greyed-out, non-clickable trashbin.

since this check is an asynchronous operation, we'll throw a spinner on every line until the check completes.

selection_161

### CODE REVIEW

**Comment by jrjohnson** [comment]
Deploy preview ready!

Built with commit 049414371595834a3c356b198c16cb109d411f4b

https://deploy-preview-2763--ilios-frontend.netlify.com

**Comment by jrjohnson** [comment]
Deploy preview ready!

Built with commit 8cda5f419e37603eb3bc84f12b382a4cb2e77d63

https://deploy-preview-2763--ilios-frontend.netlify.com

**Comment by stopfstedt** [comment]
@saschaben this can be click-tested/reviewed, despite some pending integration tests. please see if this performs acceptable for larger/deeply nested learner groups. thanks!

File: app/models/learner-group.js [hunk 1]
```diff
@@ -386,4 +386,37 @@ export default DS.Model.extend({
...
+
+  /**
+   * Checks if this group or any of its subgroups has any learners.
+   * @property hasLearnersInGroupOrSubgroups
+   * @type {Ember.computed}
+   * @public
+   */
+  hasLearnersInGroupOrSubgroups: computed('users.[]', 'children.@each.hasLearnersInGroupOrSubgroup', function() {
+    return new Promise(resolve => {
+      this.get('users').then(users => {
```
Comment (jrjohnson) [inline app/models/learner-group.js]: This can be checked without loading all of the users like 
```javascript
const userIds = this.hasMany('users').ids();
if (userIds.length) {
  resolve(true);
}
```

**Comment by saschaben** [comment]
clicktesting appears perfectly adequate in performance. :+1:
