### PR TITLE
octanifies IliosUsers component.

### LINKED ISSUE #5722: Bulk New User cancel button not working
it should close the component.

Selection_068

### PR DESCRIPTION
**Pull request by stopfstedt**
fixes #5722

### CODE REVIEW

File: app/components/new-user.js [hunk 1]
```diff
@@ -1,78 +1,166 @@
...
+  @restartableTask
+  *reload() {
+    this.currentSchoolCohorts = yield this.bestSelectedSchool?.cohorts;
+    this.cohorts = yield this.loadCohorts.perform(this.bestSelectedSchool);
+  }
+
+  @restartableTask
+  *loadSchools() {
+    const store = this.store;
+    const schools = yield store.findAll('school', { reload: true });
```
Comment (jrjohnson) [inline app/components/new-user.js:78]: An improvement may be possible here, because we always load all schools in https://github.com/ilios/frontend/blob/master/app/routes/application.js#L45 `peekRecord` could be used here synchronously replacing this with a simple `get schools` and possible making all async in this component a bit easier.

**Review by jrjohnson — COMMENTED** [review]
One maybe improvement, looks good to me. I scanned the tests and didn't dig into them too thoroughly, anything I should be looking out for there?

File: app/components/new-user.js (hunk 1 above)
Comment (stopfstedt) [reply app/components/new-user.js]: i changed it. the method will still have to be declared as either a task or an async function, since the perms check that follow the fetching of schools are async in nature.

Comment (jrjohnson) [reply app/components/new-user.js]: Oh, yea. I see that now. Ok. Accepted.

**Review by jrjohnson — APPROVED** [review]
